obstacle_range: 2.5   #robot will only update its map with information about obstacles that are within 2.5 meters of the base.
raytrace_range: 3.0    #robot will attempt to clear out space in front of it up to 3.0 meters away given a sensor reading

footprint: [[0.1075,0.0675], [0.1075,-0.0675],[-0.1075,-0.0675],[-0.1075,0.0675]]
#robot_radius: ir_of_robot
inflation_radius: 0.01  #robot will treat all paths that stay 0.55 meters or more away from obstacles as having equal obstacle cost.    #0.05

observation_sources: laser_scan_sensor     #point_cloud_sensor                    defines a list of sensors that are going to be passing information to the costmap 

laser_scan_sensor: {sensor_frame: base_frame, data_type: LaserScan, topic: LaserScan, marking: true, clearing: true}

# point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}